I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    bob "Look at this! A Magic Toaster! What could possibly go wrong?"
Exception: Sayer 'bob' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    bob "Look at this! A Magic Toaster! What could possibly go wrong?"
  File "C:\Users\haeri\Downloads\Programs\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\haeri\Downloads\Programs\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\haeri\Downloads\Programs\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bob' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Ambasuke Simulator 1.0
Sat Jun 15 21:09:14 2024
